# -*- coding: utf-8 -*-
"""GCN_install2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11q4e2Wk-kKLILhc6V0pU7WyGKG02UrfM
"""

#from google.colab import drive
#drive.mount('/content/gdrive')
#!ln -s /content/gdrive/My\ Drive/ /mydrive
import sys
lib='/content/GCN_conv_emotion/GCN'
sys.path.insert(0,lib)

import model
import sys
import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
from dataloader import IEMOCAPDataset
from model import MaskedNLLLoss, LSTMModel, GRUModel, DialogRNNModel, DialogueGCNModel
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, classification_report, precision_recall_fscore_support
import pickle
import torchtext
from torchtext.data.utils import get_tokenizer
from collections import Counter
from torchtext.vocab import Vocab
import torch
import torch.nn as nn
from torchtext.vocab import GloVe
from functools import reduce
import torch as T
#import nltk
#import torch.nn.functional as F
#from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
#import torch.nn.functional as F
#from torch.autograd import Variable
#from torch.nn.utils.rnn import pad_sequence
#from torch_geometric.nn import RGCNConv, GraphConv
#nltk.download('punkt')

"""model=pickle.load(open('/content/gdrive/MyDrive/GCN/conv-emotion/DialogueGCN/IEMOCAP_features/IEMOCAP_features.pkl', 'rb'), encoding='latin1')"""

embedding_glove = GloVe(name='6B', dim=100)

embedding_glove2 = GloVe(name='840B', dim=300)

"""pd.set_option('max_rows', 99999)
pd.set_option('max_colwidth', 400)
pd.describe_option('max_colwidth')
"""
